"""configs/sim_params.yaml loader + the cloth-XML generator that reads it.

Single place to tune actuator gains, cloth physical properties, and
camera resolution/rate -- read fresh every run (no caching) so editing
that YAML file and re-running scripts/mujoco_physics_process.py IS the
test-iteration loop, instead of hunting through Python defaults (actuator
gains) and a hand-authored MJCF (cloth) separately.
"""
from __future__ import annotations

import pathlib
from typing import Optional

import yaml

_ROOT = pathlib.Path(__file__).parent.parent
_DEFAULT_CONFIG_PATH = _ROOT / "configs" / "sim_params.yaml"
_CLOTH_XML_PATH = _ROOT / "assets" / "scene" / "_cloth_generated.xml"
_TABLE_EXCLUDE_XML_PATH = _ROOT / "assets" / "scene" / "_table_arm_excludes_generated.xml"


def load_sim_config(path: Optional[pathlib.Path] = None) -> dict:
    """Reads configs/sim_params.yaml (or `path`) fresh -- no caching, so
    every call reflects whatever's on disk right now."""
    path = pathlib.Path(path) if path is not None else _DEFAULT_CONFIG_PATH
    with open(path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)
    for key in ("actuator_gains", "cloth", "camera"):
        if key not in config:
            raise ValueError(f"{path}: missing required top-level key {key!r}")
    return config


def actuator_gain_kwargs(config: dict) -> dict:
    """config['actuator_gains'] -> the exact kwarg names robot_hand/
    mujoco_urdf.py's _build_actuated_spec()/actuated_mjcf_path()/
    build_actuated_model() accept (heavy_kp, heavy_kv, light_kp, ...)."""
    gains = config["actuator_gains"]
    kwargs = {}
    for tier in ("rigid", "heavy", "light", "wrist_roll", "finger"):
        if tier not in gains:
            continue
        kwargs[f"{tier}_kp"] = float(gains[tier]["kp"])
        kwargs[f"{tier}_kv"] = float(gains[tier]["kv"])
        if "joint_damping" in gains[tier]:
            kwargs[f"{tier}_damping"] = float(gains[tier]["joint_damping"])
        if "armature" in gains[tier]:
            kwargs[f"{tier}_armature"] = float(gains[tier]["armature"])
        if "force_limit" in gains[tier]:
            kwargs[f"{tier}_force_limit"] = float(gains[tier]["force_limit"])
    kwargs["heavy_effort_threshold"] = float(gains["heavy_effort_threshold"])
    return kwargs


def generate_cloth_xml(config: dict, out_path: pathlib.Path = _CLOTH_XML_PATH) -> pathlib.Path:
    """Writes a standalone <mujocoinclude> with just the cloth <flexcomp>,
    from config['cloth'] -- assets/scene/scene.xml <include>s this file
    instead of hardcoding the flexcomp's attributes itself. Regenerated
    (overwritten) every call; scene.xml always picks up whatever this
    wrote since MuJoCo reads the include fresh at model-compile time, no
    separate caching step needed the way the actuated robot MJCF has.
    """
    c = config["cloth"]
    count = " ".join(str(int(v)) for v in c["grid_count"])
    spacing = " ".join(str(float(v)) for v in c["spacing"])
    pos = " ".join(str(float(v)) for v in c["pos"])
    solref = " ".join(str(float(v)) for v in c["solref"])
    solimp = " ".join(str(float(v)) for v in c["solimp"])
    friction = " ".join(str(float(v)) for v in c["friction"])
    xml = f"""<mujocoinclude>
  <!-- Generated by robot_hand/sim_config.generate_cloth_xml() from
       configs/sim_params.yaml's cloth: section; edit that YAML, not
       this file directly (overwritten every run). passive="true" +
       these solref/solimp values are based on MuJoCo's drape.xml;
       changing them away from these risks the cloth sinking straight
       through the table instead of settling (confirmed the hard way,
       see assets/scene/scene.xml's own history/comments). -->
  <flexcomp type="grid" count="{count}" spacing="{spacing}" pos="{pos}"
      radius="{c['radius']}" mass="{c['mass']}" name="cloth" dim="2" material="cloth_mat">
    <contact selfcollide="auto" passive="true" solref="{solref}" solimp="{solimp}"
        friction="{friction}"/>
    <elasticity young="{c['young']}" poisson="{c['poisson']}" thickness="{c['thickness']}"
        elastic2d="both" damping="{c['damping']}"/>
  </flexcomp>
</mujocoinclude>
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(xml, encoding="utf-8")
    return out_path


def generate_table_arm_excludes_xml(
    robot_mjcf_path: pathlib.Path, out_path: pathlib.Path = _TABLE_EXCLUDE_XML_PATH,
) -> pathlib.Path:
    """Writes <exclude body1="table" body2="..."/> for every arm/hand body
    -- grasping felt too fiddly with the table itself blocking the
    approach, so this assumes the arm/hand simply never collides with the
    table (cloth still does: this only excludes TABLE<->ARM/HAND body
    pairs, nothing about the cloth<->table contact that makes the cloth
    rest on it). assets/scene/scene.xml <include>s this file's output.

    Body names are read from the ALREADY-COMPILED robot MJCF (robot_mjcf_
    path, i.e. what actuated_mjcf_path() just wrote), not guessed from the
    URDF -- MuJoCo's compiler fuses some fixed-joint-only bodies into
    their parent (confirmed asymmetric between left/right hands earlier
    this project -- right_hand_rl_dg_mount/base don't survive as separate
    bodies the way their left-side counterparts do), so a body name valid
    in the URDF can be invalid (and a load-time error) in the compiled
    model. Reading them back from the compiled model sidesteps that
    entirely: whatever's actually there is exactly what gets excluded.
    """
    import mujoco  # local import -- keeps this module importable before mujoco's own GL backend is set

    model = mujoco.MjModel.from_xml_path(str(robot_mjcf_path))
    names = [mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(model.nbody)]
    arm_hand_bodies = [n for n in names if n and ("arm" in n or "hand" in n)]

    lines = [
        "<mujocoinclude>",
        "  <!-- Generated by robot_hand/sim_config.generate_table_arm_excludes_xml();",
        "       every arm/hand body excluded from colliding with the table (cloth<->table",
        "       contact is untouched; this is TABLE<->ARM/HAND pairs only). Body names read",
        "       from the compiled robot MJCF, not the URDF; see this function's docstring",
        "       for why that distinction matters (fixed-joint body fusion). -->",
        "  <contact>",
    ]
    for body in arm_hand_bodies:
        lines.append(f'    <exclude name="exclude_table_{body}" body1="table" body2="{body}"/>')
    lines.append("  </contact>")
    lines.append("</mujocoinclude>")
    xml = "\n".join(lines) + "\n"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(xml, encoding="utf-8")
    return out_path
